import { type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode } from "react";
import { ChevronDown, Inbox, LoaderCircle, Search, X } from "lucide-react";
import { cn } from "@/lib/utils";

export function Button({ className, variant = "primary", children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger" }) {
  const styles = { primary: "bg-primary text-primary-foreground hover:bg-primary/90 shadow-sm", secondary: "border border-border bg-card text-foreground hover:bg-muted", ghost: "text-muted-foreground hover:bg-muted hover:text-foreground", danger: "bg-destructive text-destructive-foreground hover:bg-destructive/90" };
  return <button className={cn("inline-flex h-10 items-center justify-center gap-2 rounded-md px-4 text-sm font-semibold transition-colors disabled:pointer-events-none disabled:opacity-50", styles[variant], className)} {...props}>{children}</button>;
}

export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("h-10 w-full rounded-md border border-input bg-card px-3 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-ring/20", className)} {...props} />; }

export function Select({ value, onChange, options, label }: { value?: string; onChange?: (value: string) => void; options: string[]; label?: string }) { return <label className="relative block"><span className="sr-only">{label}</span><select value={value} onChange={(e) => onChange?.(e.target.value)} className="h-10 appearance-none rounded-md border border-input bg-card py-0 pl-3 pr-9 text-sm text-foreground outline-none focus:border-primary focus:ring-2 focus:ring-ring/20"><option value="">{label ?? "Select"}</option>{options.map((option) => <option key={option}>{option}</option>)}</select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-3 text-muted-foreground" /></label>; }

export function SearchBar({ value, onChange, placeholder = "Search..." }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <div className="relative min-w-0 flex-1 sm:max-w-xs"><Search size={17} className="absolute left-3 top-2.5 text-muted-foreground" /><Input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="pl-9" /></div>; }

export function PageHeader({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="font-display text-2xl font-bold text-foreground sm:text-3xl">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{action}</div>; }

const badgeStyles: Record<string, string> = { "In Stock": "bg-success/10 text-success", Completed: "bg-success/10 text-success", Active: "bg-success/10 text-success", Ready: "bg-info/10 text-info", Pending: "bg-warning/15 text-warning-foreground", Scheduled: "bg-info/10 text-info", "Low Stock": "bg-warning/15 text-warning-foreground", "Out of Stock": "bg-destructive/10 text-destructive", Draft: "bg-muted text-muted-foreground" };
export function StatusBadge({ status }: { status: string }) { return <span className={cn("inline-flex whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-semibold", badgeStyles[status] ?? "bg-muted text-muted-foreground")}>{status}</span>; }

export function KpiCard({ title, value, note, icon }: { title: string; value: string; note: string; icon: ReactNode }) { return <div className="rounded-lg border border-border bg-card p-5 shadow-card"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-muted-foreground">{title}</p><p className="mt-2 font-display text-2xl font-bold text-foreground">{value}</p></div><div className="grid size-10 place-items-center rounded-md bg-primary/8 text-primary">{icon}</div></div><p className="mt-3 text-xs text-muted-foreground">{note}</p></div>; }

export function DataTable({ columns, children }: { columns: string[]; children: ReactNode }) { return <div className="overflow-hidden rounded-lg border border-border bg-card shadow-card"><div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left"><thead><tr className="border-b border-border bg-muted/60">{columns.map((column) => <th key={column} className="whitespace-nowrap px-4 py-3 text-xs font-semibold uppercase text-muted-foreground">{column}</th>)}</tr></thead><tbody className="divide-y divide-border">{children}</tbody></table></div></div>; }

export function EmptyState({ title = "No results", description = "Try adjusting your search or filters." }: { title?: string; description?: string }) { return <div className="grid place-items-center py-16 text-center"><div className="grid size-12 place-items-center rounded-full bg-muted text-muted-foreground"><Inbox /></div><h3 className="mt-4 font-semibold text-foreground">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>; }
export function LoadingState() { return <div className="flex items-center justify-center gap-2 py-16 text-sm text-muted-foreground"><LoaderCircle className="animate-spin" size={18} /> Loading inventory...</div>; }

export function Modal({ open, onClose, title, children, footer }: { open: boolean; onClose: () => void; title: string; children: ReactNode; footer: ReactNode }) { if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-overlay/40 p-4" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-label={title} onMouseDown={(e) => e.stopPropagation()} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-lg border border-border bg-card shadow-modal"><div className="flex items-center justify-between border-b border-border px-6 py-4"><h2 className="font-display text-lg font-bold text-foreground">{title}</h2><Button variant="ghost" className="size-9 px-0" onClick={onClose} aria-label="Close"><X size={18} /></Button></div><div className="p-6">{children}</div><div className="flex justify-end gap-2 border-t border-border px-6 py-4">{footer}</div></div></div>; }
